#!/bin/bash

alias gb='git branch'

alias ga='git add'

alias gc='git commit -s -v'
alias gcm='git commit -s -m'

alias gcl='git clone'

alias gco='git checkout'

alias gcp='git cherry-pick'

alias gd='git diff'
gdf ()
{
  git diff --quiet ${@} || LESS=-eFRX git diff ${@}
}

alias gf='git fetch --all --prune'

alias gll='git pull --prune'

alias glog='git log'
alias glt="git log --pretty=format:'%C(yellow)%h %Cblue%ad %Creset%s%Cgreen [%cn] %Cred%d' --decorate --date=format:'%d-%b\`%y %H:%M %z'"
alias glth="git log --pretty=format:'%C(yellow)%h %Cblue%ad %Creset%s%Cgreen [%cn] %Cred%d' --decorate --date=format:'%d-%b\`%y %H:%M %z' | head"

alias gs='git status'
alias gsm='git status -uno'
alias gss='git status -s'

alias gcfg='git config -l'

alias gp='git push'

alias grh='git reset --hard'

alias grv='git remote -v'

_gig ()
{
	[ $# -lt 2 ] && echo "Usage: gig$1 <file-name-to-git-ignore>" && return 0

	if [ "$1" == "local" ]; then
		local f="$(git rev-parse --show-toplevel)/.gitignore"
	else
		local f="$(git config --global core.excludesfile)"
	fi
	[ ! -f "$f" ] && echo "ERROR: $1 git-ignore file not found!" && return -1

	! grep -qxF "$2" "$f" && echo "$2" >> "$f"

	return 0
}
alias gigl="_gig local"
alias gigg="_gig global"
